# Generated by Django 2.0.9 on 2019-04-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TttViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('turn', models.CharField(max_length=50)),
                ('computer_score', models.IntegerField()),
                ('username_score', models.IntegerField()),
            ],
        ),
    ]
