# Generated by Django 2.0.9 on 2019-04-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TttViews',
            new_name='TttModel',
        ),
    ]
